import uuid
from datetime import datetime

from sqlalchemy import BigInteger, DateTime, Float, ForeignKey, Identity, Integer, String, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.storage.models.base import Base


class RawBatch(Base):
    __tablename__ = "raw_batch"
    __table_args__ = {"schema": "raw"}
    raw_batch_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("ops.collect_run.run_id"), nullable=False)
    slice_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("ops.request_slice.slice_id"), nullable=False)
    source_binding_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("meta.source_binding.source_binding_id"), nullable=False)
    request_hash: Mapped[str] = mapped_column(String(128), nullable=False)
    row_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default="WRITING")
    schema_version: Mapped[str] = mapped_column(String(32), nullable=False, default="v1")
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)


class TushareTradeCal(Base):
    __tablename__ = "tushare_trade_cal"
    __table_args__ = {"schema": "raw"}

    raw_id: Mapped[int] = mapped_column("_raw_id", BigInteger, Identity(), primary_key=True)
    source: Mapped[str] = mapped_column("_source", String(32), nullable=False, default="tushare")
    source_api: Mapped[str] = mapped_column("_source_api", String(64), nullable=False)
    collect_run_id: Mapped[uuid.UUID] = mapped_column("_collect_run_id", UUID(as_uuid=True), ForeignKey("ops.collect_run.run_id"), nullable=False)
    raw_batch_id: Mapped[uuid.UUID] = mapped_column("_raw_batch_id", UUID(as_uuid=True), ForeignKey("raw.raw_batch.raw_batch_id"), nullable=False)
    fetched_at: Mapped[datetime] = mapped_column("_fetched_at", DateTime(timezone=True), nullable=False)
    request_hash: Mapped[str] = mapped_column("_request_hash", String(128), nullable=False)
    content_hash: Mapped[str] = mapped_column("_content_hash", String(128), nullable=False)
    schema_version: Mapped[str] = mapped_column("_schema_version", String(32), nullable=False, default="v1")
    exchange: Mapped[str] = mapped_column(String(16), nullable=False)
    cal_date: Mapped[str] = mapped_column(String(8), nullable=False)
    is_open: Mapped[str] = mapped_column(String(1), nullable=False)
    pretrade_date: Mapped[str | None] = mapped_column(String(8), nullable=True)


class TushareStockBasic(Base):
    __tablename__ = "tushare_stock_basic"
    __table_args__ = {"schema": "raw"}

    raw_id: Mapped[int] = mapped_column("_raw_id", BigInteger, Identity(), primary_key=True)
    source: Mapped[str] = mapped_column("_source", String(32), nullable=False, default="tushare")
    source_api: Mapped[str] = mapped_column("_source_api", String(64), nullable=False)
    collect_run_id: Mapped[uuid.UUID] = mapped_column("_collect_run_id", UUID(as_uuid=True), ForeignKey("ops.collect_run.run_id"), nullable=False)
    raw_batch_id: Mapped[uuid.UUID] = mapped_column("_raw_batch_id", UUID(as_uuid=True), ForeignKey("raw.raw_batch.raw_batch_id"), nullable=False)
    fetched_at: Mapped[datetime] = mapped_column("_fetched_at", DateTime(timezone=True), nullable=False)
    request_hash: Mapped[str] = mapped_column("_request_hash", String(128), nullable=False)
    content_hash: Mapped[str] = mapped_column("_content_hash", String(128), nullable=False)
    schema_version: Mapped[str] = mapped_column("_schema_version", String(32), nullable=False, default="v1")
    ts_code: Mapped[str] = mapped_column(String(128), nullable=False)
    symbol: Mapped[str | None] = mapped_column(String(128), nullable=True)
    name: Mapped[str | None] = mapped_column(String(128), nullable=True)
    area: Mapped[str | None] = mapped_column(String(128), nullable=True)
    industry: Mapped[str | None] = mapped_column(String(128), nullable=True)
    fullname: Mapped[str | None] = mapped_column(String(256), nullable=True)
    enname: Mapped[str | None] = mapped_column(String(256), nullable=True)
    cnspell: Mapped[str | None] = mapped_column(String(128), nullable=True)
    market: Mapped[str | None] = mapped_column(String(128), nullable=True)
    exchange: Mapped[str | None] = mapped_column(String(128), nullable=True)
    curr_type: Mapped[str | None] = mapped_column(String(128), nullable=True)
    list_status: Mapped[str | None] = mapped_column(String(128), nullable=True)
    list_date: Mapped[str | None] = mapped_column(String(128), nullable=True)
    delist_date: Mapped[str | None] = mapped_column(String(128), nullable=True)
    is_hs: Mapped[str | None] = mapped_column(String(128), nullable=True)
    act_name: Mapped[str | None] = mapped_column(String(256), nullable=True)
    act_ent_type: Mapped[str | None] = mapped_column(String(256), nullable=True)


class TushareDaily(Base):
    __tablename__ = "tushare_daily"
    __table_args__ = {"schema": "raw"}

    raw_id: Mapped[int] = mapped_column("_raw_id", BigInteger, Identity(), primary_key=True)
    source: Mapped[str] = mapped_column("_source", String(32), nullable=False, default="tushare")
    source_api: Mapped[str] = mapped_column("_source_api", String(64), nullable=False)
    collect_run_id: Mapped[uuid.UUID] = mapped_column("_collect_run_id", UUID(as_uuid=True), ForeignKey("ops.collect_run.run_id"), nullable=False)
    raw_batch_id: Mapped[uuid.UUID] = mapped_column("_raw_batch_id", UUID(as_uuid=True), ForeignKey("raw.raw_batch.raw_batch_id"), nullable=False)
    fetched_at: Mapped[datetime] = mapped_column("_fetched_at", DateTime(timezone=True), nullable=False)
    request_hash: Mapped[str] = mapped_column("_request_hash", String(128), nullable=False)
    content_hash: Mapped[str] = mapped_column("_content_hash", String(128), nullable=False)
    schema_version: Mapped[str] = mapped_column("_schema_version", String(32), nullable=False, default="v1")
    ts_code: Mapped[str] = mapped_column(String(16), nullable=False)
    trade_date: Mapped[str] = mapped_column(String(8), nullable=False)
    open: Mapped[float | None] = mapped_column(Float, nullable=True)
    high: Mapped[float | None] = mapped_column(Float, nullable=True)
    low: Mapped[float | None] = mapped_column(Float, nullable=True)
    close: Mapped[float | None] = mapped_column(Float, nullable=True)
    pre_close: Mapped[float | None] = mapped_column(Float, nullable=True)
    change: Mapped[float | None] = mapped_column(Float, nullable=True)
    pct_chg: Mapped[float | None] = mapped_column(Float, nullable=True)
    vol: Mapped[float | None] = mapped_column(Float, nullable=True)
    amount: Mapped[float | None] = mapped_column(Float, nullable=True)
    ah_vol: Mapped[float | None] = mapped_column(Float, nullable=True)
    ah_amount: Mapped[float | None] = mapped_column(Float, nullable=True)


class TushareAdjFactor(Base):
    __tablename__ = "tushare_adj_factor"
    __table_args__ = {"schema": "raw"}

    raw_id: Mapped[int] = mapped_column("_raw_id", BigInteger, Identity(), primary_key=True)
    source: Mapped[str] = mapped_column("_source", String(32), nullable=False, default="tushare")
    source_api: Mapped[str] = mapped_column("_source_api", String(64), nullable=False)
    collect_run_id: Mapped[uuid.UUID] = mapped_column("_collect_run_id", UUID(as_uuid=True), ForeignKey("ops.collect_run.run_id"), nullable=False)
    raw_batch_id: Mapped[uuid.UUID] = mapped_column("_raw_batch_id", UUID(as_uuid=True), ForeignKey("raw.raw_batch.raw_batch_id"), nullable=False)
    fetched_at: Mapped[datetime] = mapped_column("_fetched_at", DateTime(timezone=True), nullable=False)
    request_hash: Mapped[str] = mapped_column("_request_hash", String(128), nullable=False)
    content_hash: Mapped[str] = mapped_column("_content_hash", String(128), nullable=False)
    schema_version: Mapped[str] = mapped_column("_schema_version", String(32), nullable=False, default="v1")
    ts_code: Mapped[str] = mapped_column(String(16), nullable=False)
    trade_date: Mapped[str] = mapped_column(String(8), nullable=False)
    adj_factor: Mapped[float | None] = mapped_column(Float, nullable=True)


class TushareDailyBasic(Base):
    __tablename__ = "tushare_daily_basic"
    __table_args__ = {"schema": "raw"}

    raw_id: Mapped[int] = mapped_column("_raw_id", BigInteger, Identity(), primary_key=True)
    source: Mapped[str] = mapped_column("_source", String(32), nullable=False, default="tushare")
    source_api: Mapped[str] = mapped_column("_source_api", String(64), nullable=False)
    collect_run_id: Mapped[uuid.UUID] = mapped_column("_collect_run_id", UUID(as_uuid=True), ForeignKey("ops.collect_run.run_id"), nullable=False)
    raw_batch_id: Mapped[uuid.UUID] = mapped_column("_raw_batch_id", UUID(as_uuid=True), ForeignKey("raw.raw_batch.raw_batch_id"), nullable=False)
    fetched_at: Mapped[datetime] = mapped_column("_fetched_at", DateTime(timezone=True), nullable=False)
    request_hash: Mapped[str] = mapped_column("_request_hash", String(128), nullable=False)
    content_hash: Mapped[str] = mapped_column("_content_hash", String(128), nullable=False)
    schema_version: Mapped[str] = mapped_column("_schema_version", String(32), nullable=False, default="v1")
    ts_code: Mapped[str] = mapped_column(String(16), nullable=False)
    trade_date: Mapped[str] = mapped_column(String(8), nullable=False)
    close: Mapped[float | None] = mapped_column(Float, nullable=True)
    turnover_rate: Mapped[float | None] = mapped_column(Float, nullable=True)
    turnover_rate_f: Mapped[float | None] = mapped_column(Float, nullable=True)
    volume_ratio: Mapped[float | None] = mapped_column(Float, nullable=True)
    pe: Mapped[float | None] = mapped_column(Float, nullable=True)
    pe_ttm: Mapped[float | None] = mapped_column(Float, nullable=True)
    pb: Mapped[float | None] = mapped_column(Float, nullable=True)
    ps: Mapped[float | None] = mapped_column(Float, nullable=True)
    ps_ttm: Mapped[float | None] = mapped_column(Float, nullable=True)
    dv_ratio: Mapped[float | None] = mapped_column(Float, nullable=True)
    dv_ttm: Mapped[float | None] = mapped_column(Float, nullable=True)
    total_share: Mapped[float | None] = mapped_column(Float, nullable=True)
    float_share: Mapped[float | None] = mapped_column(Float, nullable=True)
    free_share: Mapped[float | None] = mapped_column(Float, nullable=True)
    total_mv: Mapped[float | None] = mapped_column(Float, nullable=True)
    circ_mv: Mapped[float | None] = mapped_column(Float, nullable=True)
    limit_status: Mapped[int | None] = mapped_column(Integer, nullable=True)


class TushareSuspendD(Base):
    __tablename__ = "tushare_suspend_d"
    __table_args__ = {"schema": "raw"}

    raw_id: Mapped[int] = mapped_column("_raw_id", BigInteger, Identity(), primary_key=True)
    source: Mapped[str] = mapped_column("_source", String(32), nullable=False, default="tushare")
    source_api: Mapped[str] = mapped_column("_source_api", String(64), nullable=False)
    collect_run_id: Mapped[uuid.UUID] = mapped_column("_collect_run_id", UUID(as_uuid=True), ForeignKey("ops.collect_run.run_id"), nullable=False)
    raw_batch_id: Mapped[uuid.UUID] = mapped_column("_raw_batch_id", UUID(as_uuid=True), ForeignKey("raw.raw_batch.raw_batch_id"), nullable=False)
    fetched_at: Mapped[datetime] = mapped_column("_fetched_at", DateTime(timezone=True), nullable=False)
    request_hash: Mapped[str] = mapped_column("_request_hash", String(128), nullable=False)
    content_hash: Mapped[str] = mapped_column("_content_hash", String(128), nullable=False)
    schema_version: Mapped[str] = mapped_column("_schema_version", String(32), nullable=False, default="v1")
    ts_code: Mapped[str] = mapped_column(String(16), nullable=False)
    trade_date: Mapped[str] = mapped_column(String(8), nullable=False)
    suspend_timing: Mapped[str | None] = mapped_column(String(64), nullable=True)
    suspend_type: Mapped[str] = mapped_column(String(8), nullable=False)


class TushareStkLimit(Base):
    __tablename__ = "tushare_stk_limit"
    __table_args__ = {"schema": "raw"}

    raw_id: Mapped[int] = mapped_column("_raw_id", BigInteger, Identity(), primary_key=True)
    source: Mapped[str] = mapped_column("_source", String(32), nullable=False, default="tushare")
    source_api: Mapped[str] = mapped_column("_source_api", String(64), nullable=False)
    collect_run_id: Mapped[uuid.UUID] = mapped_column("_collect_run_id", UUID(as_uuid=True), ForeignKey("ops.collect_run.run_id"), nullable=False)
    raw_batch_id: Mapped[uuid.UUID] = mapped_column("_raw_batch_id", UUID(as_uuid=True), ForeignKey("raw.raw_batch.raw_batch_id"), nullable=False)
    fetched_at: Mapped[datetime] = mapped_column("_fetched_at", DateTime(timezone=True), nullable=False)
    request_hash: Mapped[str] = mapped_column("_request_hash", String(128), nullable=False)
    content_hash: Mapped[str] = mapped_column("_content_hash", String(128), nullable=False)
    schema_version: Mapped[str] = mapped_column("_schema_version", String(32), nullable=False, default="v1")
    trade_date: Mapped[str] = mapped_column(String(8), nullable=False)
    ts_code: Mapped[str] = mapped_column(String(16), nullable=False)
    pre_close: Mapped[float | None] = mapped_column(Float, nullable=True)
    up_limit: Mapped[float | None] = mapped_column(Float, nullable=True)
    down_limit: Mapped[float | None] = mapped_column(Float, nullable=True)


class TushareStkMins(Base):
    __tablename__ = "tushare_stk_mins"
    __table_args__ = {"schema": "raw"}

    raw_id: Mapped[int] = mapped_column("_raw_id", BigInteger, Identity(), primary_key=True)
    source: Mapped[str] = mapped_column("_source", String(32), nullable=False, default="tushare")
    source_api: Mapped[str] = mapped_column("_source_api", String(64), nullable=False)
    collect_run_id: Mapped[uuid.UUID] = mapped_column("_collect_run_id", UUID(as_uuid=True), ForeignKey("ops.collect_run.run_id"), nullable=False)
    raw_batch_id: Mapped[uuid.UUID] = mapped_column("_raw_batch_id", UUID(as_uuid=True), ForeignKey("raw.raw_batch.raw_batch_id"), nullable=False)
    fetched_at: Mapped[datetime] = mapped_column("_fetched_at", DateTime(timezone=True), nullable=False)
    request_hash: Mapped[str] = mapped_column("_request_hash", String(128), nullable=False)
    content_hash: Mapped[str] = mapped_column("_content_hash", String(128), nullable=False)
    schema_version: Mapped[str] = mapped_column("_schema_version", String(32), nullable=False, default="v1")
    ts_code: Mapped[str] = mapped_column(String(16), nullable=False)
    trade_time: Mapped[str] = mapped_column(String(19), nullable=False)
    frequency: Mapped[str] = mapped_column(String(16), nullable=False)
    open: Mapped[float | None] = mapped_column(Float, nullable=True)
    close: Mapped[float | None] = mapped_column(Float, nullable=True)
    high: Mapped[float | None] = mapped_column(Float, nullable=True)
    low: Mapped[float | None] = mapped_column(Float, nullable=True)
    vol: Mapped[float | None] = mapped_column(Float, nullable=True)
    amount: Mapped[float | None] = mapped_column(Float, nullable=True)


class TushareIncome(Base):
    __tablename__ = "tushare_income"
    __table_args__ = {"schema": "raw"}

    raw_id: Mapped[int] = mapped_column("_raw_id", BigInteger, Identity(), primary_key=True)
    source: Mapped[str] = mapped_column("_source", String(32), nullable=False, default="tushare")
    source_api: Mapped[str] = mapped_column("_source_api", String(64), nullable=False)
    collect_run_id: Mapped[uuid.UUID] = mapped_column("_collect_run_id", UUID(as_uuid=True), ForeignKey("ops.collect_run.run_id"), nullable=False)
    raw_batch_id: Mapped[uuid.UUID] = mapped_column("_raw_batch_id", UUID(as_uuid=True), ForeignKey("raw.raw_batch.raw_batch_id"), nullable=False)
    fetched_at: Mapped[datetime] = mapped_column("_fetched_at", DateTime(timezone=True), nullable=False)
    request_hash: Mapped[str] = mapped_column("_request_hash", String(128), nullable=False)
    content_hash: Mapped[str] = mapped_column("_content_hash", String(128), nullable=False)
    schema_version: Mapped[str] = mapped_column("_schema_version", String(32), nullable=False, default="v1")
    ts_code: Mapped[str] = mapped_column(String(16), nullable=False)
    ann_date: Mapped[str | None] = mapped_column(String(8), nullable=True)
    f_ann_date: Mapped[str | None] = mapped_column(String(8), nullable=True)
    end_date: Mapped[str] = mapped_column(String(8), nullable=False)
    report_type: Mapped[str | None] = mapped_column(String(8), nullable=True)
    comp_type: Mapped[str | None] = mapped_column(String(8), nullable=True)
    end_type: Mapped[str | None] = mapped_column(String(8), nullable=True)
    update_flag: Mapped[str | None] = mapped_column(String(8), nullable=True)
    basic_eps: Mapped[float | None] = mapped_column(Float, nullable=True)
    diluted_eps: Mapped[float | None] = mapped_column(Float, nullable=True)
    total_revenue: Mapped[float | None] = mapped_column(Float, nullable=True)
    revenue: Mapped[float | None] = mapped_column(Float, nullable=True)
    int_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    prem_earned: Mapped[float | None] = mapped_column(Float, nullable=True)
    comm_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    n_commis_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    n_oth_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    n_oth_b_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    prem_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    out_prem: Mapped[float | None] = mapped_column(Float, nullable=True)
    une_prem_reser: Mapped[float | None] = mapped_column(Float, nullable=True)
    reins_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    n_sec_tb_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    n_sec_uw_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    n_asset_mg_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    oth_b_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    fv_value_chg_gain: Mapped[float | None] = mapped_column(Float, nullable=True)
    invest_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    ass_invest_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    forex_gain: Mapped[float | None] = mapped_column(Float, nullable=True)
    total_cogs: Mapped[float | None] = mapped_column(Float, nullable=True)
    oper_cost: Mapped[float | None] = mapped_column(Float, nullable=True)
    int_exp: Mapped[float | None] = mapped_column(Float, nullable=True)
    comm_exp: Mapped[float | None] = mapped_column(Float, nullable=True)
    biz_tax_surchg: Mapped[float | None] = mapped_column(Float, nullable=True)
    sell_exp: Mapped[float | None] = mapped_column(Float, nullable=True)
    admin_exp: Mapped[float | None] = mapped_column(Float, nullable=True)
    fin_exp: Mapped[float | None] = mapped_column(Float, nullable=True)
    assets_impair_loss: Mapped[float | None] = mapped_column(Float, nullable=True)
    prem_refund: Mapped[float | None] = mapped_column(Float, nullable=True)
    compens_payout: Mapped[float | None] = mapped_column(Float, nullable=True)
    reser_insur_liab: Mapped[float | None] = mapped_column(Float, nullable=True)
    div_payt: Mapped[float | None] = mapped_column(Float, nullable=True)
    reins_exp: Mapped[float | None] = mapped_column(Float, nullable=True)
    oper_exp: Mapped[float | None] = mapped_column(Float, nullable=True)
    compens_payout_refu: Mapped[float | None] = mapped_column(Float, nullable=True)
    insur_reser_refu: Mapped[float | None] = mapped_column(Float, nullable=True)
    reins_cost_refund: Mapped[float | None] = mapped_column(Float, nullable=True)
    other_bus_cost: Mapped[float | None] = mapped_column(Float, nullable=True)
    operate_profit: Mapped[float | None] = mapped_column(Float, nullable=True)
    non_oper_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    non_oper_exp: Mapped[float | None] = mapped_column(Float, nullable=True)
    nca_disploss: Mapped[float | None] = mapped_column(Float, nullable=True)
    total_profit: Mapped[float | None] = mapped_column(Float, nullable=True)
    income_tax: Mapped[float | None] = mapped_column(Float, nullable=True)
    n_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    n_income_attr_p: Mapped[float | None] = mapped_column(Float, nullable=True)
    minority_gain: Mapped[float | None] = mapped_column(Float, nullable=True)
    oth_compr_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    t_compr_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    compr_inc_attr_p: Mapped[float | None] = mapped_column(Float, nullable=True)
    compr_inc_attr_m_s: Mapped[float | None] = mapped_column(Float, nullable=True)
    ebit: Mapped[float | None] = mapped_column(Float, nullable=True)
    ebitda: Mapped[float | None] = mapped_column(Float, nullable=True)
    insurance_exp: Mapped[float | None] = mapped_column(Float, nullable=True)
    undist_profit: Mapped[float | None] = mapped_column(Float, nullable=True)
    distable_profit: Mapped[float | None] = mapped_column(Float, nullable=True)
    rd_exp: Mapped[float | None] = mapped_column(Float, nullable=True)
    fin_exp_int_exp: Mapped[float | None] = mapped_column(Float, nullable=True)
    fin_exp_int_inc: Mapped[float | None] = mapped_column(Float, nullable=True)
    transfer_surplus_rese: Mapped[float | None] = mapped_column(Float, nullable=True)
    transfer_housing_imprest: Mapped[float | None] = mapped_column(Float, nullable=True)
    transfer_oth: Mapped[float | None] = mapped_column(Float, nullable=True)
    adj_lossgain: Mapped[float | None] = mapped_column(Float, nullable=True)
    withdra_legal_surplus: Mapped[float | None] = mapped_column(Float, nullable=True)
    withdra_legal_pubfund: Mapped[float | None] = mapped_column(Float, nullable=True)
    withdra_biz_devfund: Mapped[float | None] = mapped_column(Float, nullable=True)
    withdra_rese_fund: Mapped[float | None] = mapped_column(Float, nullable=True)
    withdra_oth_ersu: Mapped[float | None] = mapped_column(Float, nullable=True)
    workers_welfare: Mapped[float | None] = mapped_column(Float, nullable=True)
    distr_profit_shrhder: Mapped[float | None] = mapped_column(Float, nullable=True)
    prfshare_payable_dvd: Mapped[float | None] = mapped_column(Float, nullable=True)
    comshare_payable_dvd: Mapped[float | None] = mapped_column(Float, nullable=True)
    capit_comstock_div: Mapped[float | None] = mapped_column(Float, nullable=True)
    net_after_nr_lp_correct: Mapped[float | None] = mapped_column(Float, nullable=True)
    credit_impa_loss: Mapped[float | None] = mapped_column(Float, nullable=True)
    net_expo_hedging_benefits: Mapped[float | None] = mapped_column(Float, nullable=True)
    oth_impair_loss_assets: Mapped[float | None] = mapped_column(Float, nullable=True)
    total_opcost: Mapped[float | None] = mapped_column(Float, nullable=True)
    amodcost_fin_assets: Mapped[float | None] = mapped_column(Float, nullable=True)
    oth_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    asset_disp_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    continued_net_profit: Mapped[float | None] = mapped_column(Float, nullable=True)
    end_net_profit: Mapped[float | None] = mapped_column(Float, nullable=True)


class TushareFinaIndicator(Base):
    __tablename__ = "tushare_fina_indicator"
    __table_args__ = {"schema": "raw"}

    raw_id: Mapped[int] = mapped_column("_raw_id", BigInteger, Identity(), primary_key=True)
    source: Mapped[str] = mapped_column("_source", String(32), nullable=False, default="tushare")
    source_api: Mapped[str] = mapped_column("_source_api", String(64), nullable=False)
    collect_run_id: Mapped[uuid.UUID] = mapped_column("_collect_run_id", UUID(as_uuid=True), ForeignKey("ops.collect_run.run_id"), nullable=False)
    raw_batch_id: Mapped[uuid.UUID] = mapped_column("_raw_batch_id", UUID(as_uuid=True), ForeignKey("raw.raw_batch.raw_batch_id"), nullable=False)
    fetched_at: Mapped[datetime] = mapped_column("_fetched_at", DateTime(timezone=True), nullable=False)
    request_hash: Mapped[str] = mapped_column("_request_hash", String(128), nullable=False)
    content_hash: Mapped[str] = mapped_column("_content_hash", String(128), nullable=False)
    schema_version: Mapped[str] = mapped_column("_schema_version", String(32), nullable=False, default="v1")
    ts_code: Mapped[str] = mapped_column(String(16), nullable=False)
    ann_date: Mapped[str | None] = mapped_column(String(8), nullable=True)
    end_date: Mapped[str] = mapped_column(String(8), nullable=False)
    update_flag: Mapped[str | None] = mapped_column(String(8), nullable=True)
    eps: Mapped[float | None] = mapped_column(Float, nullable=True)
    dt_eps: Mapped[float | None] = mapped_column(Float, nullable=True)
    total_revenue_ps: Mapped[float | None] = mapped_column(Float, nullable=True)
    revenue_ps: Mapped[float | None] = mapped_column(Float, nullable=True)
    capital_rese_ps: Mapped[float | None] = mapped_column(Float, nullable=True)
    surplus_rese_ps: Mapped[float | None] = mapped_column(Float, nullable=True)
    undist_profit_ps: Mapped[float | None] = mapped_column(Float, nullable=True)
    extra_item: Mapped[float | None] = mapped_column(Float, nullable=True)
    profit_dedt: Mapped[float | None] = mapped_column(Float, nullable=True)
    gross_margin: Mapped[float | None] = mapped_column(Float, nullable=True)
    current_ratio: Mapped[float | None] = mapped_column(Float, nullable=True)
    quick_ratio: Mapped[float | None] = mapped_column(Float, nullable=True)
    cash_ratio: Mapped[float | None] = mapped_column(Float, nullable=True)
    invturn_days: Mapped[float | None] = mapped_column(Float, nullable=True)
    arturn_days: Mapped[float | None] = mapped_column(Float, nullable=True)
    inv_turn: Mapped[float | None] = mapped_column(Float, nullable=True)
    ar_turn: Mapped[float | None] = mapped_column(Float, nullable=True)
    ca_turn: Mapped[float | None] = mapped_column(Float, nullable=True)
    fa_turn: Mapped[float | None] = mapped_column(Float, nullable=True)
    assets_turn: Mapped[float | None] = mapped_column(Float, nullable=True)
    op_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    valuechange_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    interst_income: Mapped[float | None] = mapped_column(Float, nullable=True)
    daa: Mapped[float | None] = mapped_column(Float, nullable=True)
    ebit: Mapped[float | None] = mapped_column(Float, nullable=True)
    ebitda: Mapped[float | None] = mapped_column(Float, nullable=True)
    fcff: Mapped[float | None] = mapped_column(Float, nullable=True)
    fcfe: Mapped[float | None] = mapped_column(Float, nullable=True)
    current_exint: Mapped[float | None] = mapped_column(Float, nullable=True)
    noncurrent_exint: Mapped[float | None] = mapped_column(Float, nullable=True)
    interestdebt: Mapped[float | None] = mapped_column(Float, nullable=True)
    netdebt: Mapped[float | None] = mapped_column(Float, nullable=True)
    tangible_asset: Mapped[float | None] = mapped_column(Float, nullable=True)
    working_capital: Mapped[float | None] = mapped_column(Float, nullable=True)
    networking_capital: Mapped[float | None] = mapped_column(Float, nullable=True)
    invest_capital: Mapped[float | None] = mapped_column(Float, nullable=True)
    retained_earnings: Mapped[float | None] = mapped_column(Float, nullable=True)
    diluted2_eps: Mapped[float | None] = mapped_column(Float, nullable=True)
    bps: Mapped[float | None] = mapped_column(Float, nullable=True)
    ocfps: Mapped[float | None] = mapped_column(Float, nullable=True)
    retainedps: Mapped[float | None] = mapped_column(Float, nullable=True)
    cfps: Mapped[float | None] = mapped_column(Float, nullable=True)
    ebit_ps: Mapped[float | None] = mapped_column(Float, nullable=True)
    fcff_ps: Mapped[float | None] = mapped_column(Float, nullable=True)
    fcfe_ps: Mapped[float | None] = mapped_column(Float, nullable=True)
    netprofit_margin: Mapped[float | None] = mapped_column(Float, nullable=True)
    grossprofit_margin: Mapped[float | None] = mapped_column(Float, nullable=True)
    cogs_of_sales: Mapped[float | None] = mapped_column(Float, nullable=True)
    expense_of_sales: Mapped[float | None] = mapped_column(Float, nullable=True)
    profit_to_gr: Mapped[float | None] = mapped_column(Float, nullable=True)
    saleexp_to_gr: Mapped[float | None] = mapped_column(Float, nullable=True)
    adminexp_of_gr: Mapped[float | None] = mapped_column(Float, nullable=True)
    finaexp_of_gr: Mapped[float | None] = mapped_column(Float, nullable=True)
    impai_ttm: Mapped[float | None] = mapped_column(Float, nullable=True)
    gc_of_gr: Mapped[float | None] = mapped_column(Float, nullable=True)
    op_of_gr: Mapped[float | None] = mapped_column(Float, nullable=True)
    ebit_of_gr: Mapped[float | None] = mapped_column(Float, nullable=True)
    roe: Mapped[float | None] = mapped_column(Float, nullable=True)
    roe_waa: Mapped[float | None] = mapped_column(Float, nullable=True)
    roe_dt: Mapped[float | None] = mapped_column(Float, nullable=True)
    roa: Mapped[float | None] = mapped_column(Float, nullable=True)
    npta: Mapped[float | None] = mapped_column(Float, nullable=True)
    roic: Mapped[float | None] = mapped_column(Float, nullable=True)
    roe_yearly: Mapped[float | None] = mapped_column(Float, nullable=True)
    roa2_yearly: Mapped[float | None] = mapped_column(Float, nullable=True)
    roe_avg: Mapped[float | None] = mapped_column(Float, nullable=True)
    opincome_of_ebt: Mapped[float | None] = mapped_column(Float, nullable=True)
    investincome_of_ebt: Mapped[float | None] = mapped_column(Float, nullable=True)
    n_op_profit_of_ebt: Mapped[float | None] = mapped_column(Float, nullable=True)
    tax_to_ebt: Mapped[float | None] = mapped_column(Float, nullable=True)
    dtprofit_to_profit: Mapped[float | None] = mapped_column(Float, nullable=True)
    salescash_to_or: Mapped[float | None] = mapped_column(Float, nullable=True)
    ocf_to_or: Mapped[float | None] = mapped_column(Float, nullable=True)
    ocf_to_opincome: Mapped[float | None] = mapped_column(Float, nullable=True)
    capitalized_to_da: Mapped[float | None] = mapped_column(Float, nullable=True)
    debt_to_assets: Mapped[float | None] = mapped_column(Float, nullable=True)
    assets_to_eqt: Mapped[float | None] = mapped_column(Float, nullable=True)
    dp_assets_to_eqt: Mapped[float | None] = mapped_column(Float, nullable=True)
    ca_to_assets: Mapped[float | None] = mapped_column(Float, nullable=True)
    nca_to_assets: Mapped[float | None] = mapped_column(Float, nullable=True)
    tbassets_to_totalassets: Mapped[float | None] = mapped_column(Float, nullable=True)
    int_to_talcap: Mapped[float | None] = mapped_column(Float, nullable=True)
    eqt_to_talcapital: Mapped[float | None] = mapped_column(Float, nullable=True)
    currentdebt_to_debt: Mapped[float | None] = mapped_column(Float, nullable=True)
    longdeb_to_debt: Mapped[float | None] = mapped_column(Float, nullable=True)
    ocf_to_shortdebt: Mapped[float | None] = mapped_column(Float, nullable=True)
    debt_to_eqt: Mapped[float | None] = mapped_column(Float, nullable=True)
    eqt_to_debt: Mapped[float | None] = mapped_column(Float, nullable=True)
    eqt_to_interestdebt: Mapped[float | None] = mapped_column(Float, nullable=True)
    tangibleasset_to_debt: Mapped[float | None] = mapped_column(Float, nullable=True)
    tangasset_to_intdebt: Mapped[float | None] = mapped_column(Float, nullable=True)
    tangibleasset_to_netdebt: Mapped[float | None] = mapped_column(Float, nullable=True)
    ocf_to_debt: Mapped[float | None] = mapped_column(Float, nullable=True)
    ocf_to_interestdebt: Mapped[float | None] = mapped_column(Float, nullable=True)
    ocf_to_netdebt: Mapped[float | None] = mapped_column(Float, nullable=True)
    ebit_to_interest: Mapped[float | None] = mapped_column(Float, nullable=True)
    longdebt_to_workingcapital: Mapped[float | None] = mapped_column(Float, nullable=True)
    ebitda_to_debt: Mapped[float | None] = mapped_column(Float, nullable=True)
    turn_days: Mapped[float | None] = mapped_column(Float, nullable=True)
    roa_yearly: Mapped[float | None] = mapped_column(Float, nullable=True)
    roa_dp: Mapped[float | None] = mapped_column(Float, nullable=True)
    fixed_assets: Mapped[float | None] = mapped_column(Float, nullable=True)
    profit_prefin_exp: Mapped[float | None] = mapped_column(Float, nullable=True)
    non_op_profit: Mapped[float | None] = mapped_column(Float, nullable=True)
    op_to_ebt: Mapped[float | None] = mapped_column(Float, nullable=True)
    nop_to_ebt: Mapped[float | None] = mapped_column(Float, nullable=True)
    ocf_to_profit: Mapped[float | None] = mapped_column(Float, nullable=True)
    cash_to_liqdebt: Mapped[float | None] = mapped_column(Float, nullable=True)
    cash_to_liqdebt_withinterest: Mapped[float | None] = mapped_column(Float, nullable=True)
    op_to_liqdebt: Mapped[float | None] = mapped_column(Float, nullable=True)
    op_to_debt: Mapped[float | None] = mapped_column(Float, nullable=True)
    roic_yearly: Mapped[float | None] = mapped_column(Float, nullable=True)
    total_fa_trun: Mapped[float | None] = mapped_column(Float, nullable=True)
    profit_to_op: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_opincome: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_investincome: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_dtprofit: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_eps: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_netprofit_margin: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_gsprofit_margin: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_exp_to_sales: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_profit_to_gr: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_saleexp_to_gr: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_adminexp_to_gr: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_finaexp_to_gr: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_impair_to_gr_ttm: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_gc_to_gr: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_op_to_gr: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_roe: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_dt_roe: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_npta: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_opincome_to_ebt: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_investincome_to_ebt: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_dtprofit_to_profit: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_salescash_to_or: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_ocf_to_sales: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_ocf_to_or: Mapped[float | None] = mapped_column(Float, nullable=True)
    basic_eps_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    dt_eps_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    cfps_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    op_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    ebt_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    netprofit_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    dt_netprofit_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    ocf_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    roe_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    bps_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    assets_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    eqt_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    tr_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    or_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_gr_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_gr_qoq: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_sales_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_sales_qoq: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_op_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_op_qoq: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_profit_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_profit_qoq: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_netprofit_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    q_netprofit_qoq: Mapped[float | None] = mapped_column(Float, nullable=True)
    equity_yoy: Mapped[float | None] = mapped_column(Float, nullable=True)
    rd_exp: Mapped[float | None] = mapped_column(Float, nullable=True)
