"""P4 core clean, quality and lineage runtime

Revision ID: 0009_p4_core
Revises: 0008_ops_control
Create Date: 2026-07-28
"""
import uuid

from alembic import op

revision = "0009_p4_core"
down_revision = "0008_ops_control"
branch_labels = None
depends_on = None

NS = uuid.UUID("f49c0ed2-6b6d-4a65-9e8d-03de74809391")


def uid(value: str) -> uuid.UUID:
    return uuid.uuid5(NS, value)


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS clean")

    op.execute('''
        CREATE TABLE ops.clean_run (
            clean_run_id UUID PRIMARY KEY,
            task_id UUID NOT NULL REFERENCES ops.collect_task(task_id),
            run_number INTEGER NOT NULL,
            worker_id VARCHAR(128),
            trace_id UUID NOT NULL,
            data_item_id UUID NOT NULL REFERENCES meta.data_item(data_item_id),
            status VARCHAR(32) NOT NULL,
            mapping_version VARCHAR(32) NOT NULL,
            normalization_version VARCHAR(32) NOT NULL,
            app_version VARCHAR(64) NOT NULL,
            code_revision VARCHAR(64) NOT NULL,
            started_at TIMESTAMPTZ NOT NULL,
            heartbeat_at TIMESTAMPTZ,
            finished_at TIMESTAMPTZ,
            raw_rows BIGINT NOT NULL DEFAULT 0,
            accepted_rows BIGINT NOT NULL DEFAULT 0,
            skipped_rows BIGINT NOT NULL DEFAULT 0,
            rejected_rows BIGINT NOT NULL DEFAULT 0,
            error_type VARCHAR(64),
            error_message TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_clean_run_task_number UNIQUE(task_id, run_number)
        )
    ''')

    op.execute('''
        CREATE TABLE clean.clean_batch (
            clean_batch_id UUID PRIMARY KEY,
            clean_run_id UUID NOT NULL REFERENCES ops.clean_run(clean_run_id),
            source_task_id UUID NOT NULL REFERENCES ops.collect_task(task_id),
            data_item_id UUID NOT NULL REFERENCES meta.data_item(data_item_id),
            trace_id UUID NOT NULL,
            scope_key VARCHAR(512) NOT NULL,
            scope_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            status VARCHAR(32) NOT NULL,
            mapping_version VARCHAR(32) NOT NULL,
            normalization_version VARCHAR(32) NOT NULL,
            quality_rule_version VARCHAR(32) NOT NULL,
            app_version VARCHAR(64) NOT NULL,
            code_revision VARCHAR(64) NOT NULL,
            raw_rows BIGINT NOT NULL DEFAULT 0,
            accepted_rows BIGINT NOT NULL DEFAULT 0,
            skipped_rows BIGINT NOT NULL DEFAULT 0,
            rejected_rows BIGINT NOT NULL DEFAULT 0,
            candidate_rows BIGINT NOT NULL DEFAULT 0,
            published_rows BIGINT NOT NULL DEFAULT 0,
            unchanged_rows BIGINT NOT NULL DEFAULT 0,
            changed_rows BIGINT NOT NULL DEFAULT 0,
            warning_rows BIGINT NOT NULL DEFAULT 0,
            blocked_rows BIGINT NOT NULL DEFAULT 0,
            candidate_content_hash VARCHAR(128),
            published_content_hash VARCHAR(128),
            published_quality_run_id UUID,
            current_quality_run_id UUID,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            validated_at TIMESTAMPTZ,
            published_at TIMESTAMPTZ,
            superseded_at TIMESTAMPTZ,
            superseded_by_clean_batch_id UUID REFERENCES clean.clean_batch(clean_batch_id),
            CONSTRAINT uq_clean_batch_source_scope_version UNIQUE(
                data_item_id, scope_key, mapping_version, normalization_version, source_task_id
            )
        )
    ''')
    op.execute("CREATE INDEX ix_clean_batch_item_scope_time ON clean.clean_batch(data_item_id, scope_key, created_at DESC)")
    op.execute("CREATE INDEX ix_clean_batch_trace ON clean.clean_batch(trace_id)")

    op.execute('''
        CREATE TABLE clean.clean_batch_input (
            clean_batch_id UUID NOT NULL REFERENCES clean.clean_batch(clean_batch_id),
            raw_batch_id UUID NOT NULL REFERENCES raw.raw_batch(raw_batch_id),
            input_role VARCHAR(16) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY(clean_batch_id, raw_batch_id, input_role)
        )
    ''')
    op.execute("CREATE INDEX ix_clean_batch_input_raw ON clean.clean_batch_input(raw_batch_id)")

    op.execute('''
        CREATE TABLE clean.clean_candidate_row (
            candidate_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            clean_batch_id UUID NOT NULL REFERENCES clean.clean_batch(clean_batch_id),
            raw_batch_id UUID NOT NULL REFERENCES raw.raw_batch(raw_batch_id),
            business_key_hash VARCHAR(128) NOT NULL,
            business_key JSONB NOT NULL,
            payload JSONB NOT NULL,
            source VARCHAR(32) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_clean_candidate_business_key UNIQUE(clean_batch_id, business_key_hash)
        )
    ''')

    op.execute('''
        CREATE TABLE clean.trade_calendar (
            exchange_code VARCHAR(8) NOT NULL,
            calendar_date DATE NOT NULL,
            is_open BOOLEAN NOT NULL,
            previous_trade_date DATE,
            _clean_batch_id UUID NOT NULL REFERENCES clean.clean_batch(clean_batch_id),
            _source VARCHAR(32) NOT NULL,
            _available_at TIMESTAMPTZ NOT NULL,
            _quality_status VARCHAR(16) NOT NULL,
            _mapping_version VARCHAR(32) NOT NULL,
            _normalization_version VARCHAR(32) NOT NULL,
            _quality_rule_version VARCHAR(32) NOT NULL,
            _created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            _updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY(exchange_code, calendar_date)
        )
    ''')
    op.execute("CREATE INDEX ix_clean_trade_calendar_date_exchange ON clean.trade_calendar(calendar_date, exchange_code)")

    op.execute('''
        CREATE TABLE clean.security_master (
            security_code VARCHAR(16) PRIMARY KEY,
            symbol VARCHAR(16) NOT NULL,
            name VARCHAR(128),
            area VARCHAR(64),
            industry_name VARCHAR(128),
            full_name VARCHAR(256),
            english_name VARCHAR(256),
            cn_spell VARCHAR(64),
            market VARCHAR(32),
            exchange_code VARCHAR(8) NOT NULL,
            currency_code VARCHAR(8),
            list_status VARCHAR(8) NOT NULL,
            list_date DATE,
            delist_date DATE,
            hsgt_status VARCHAR(8),
            actual_controller_name VARCHAR(256),
            actual_controller_entity_type VARCHAR(128),
            _clean_batch_id UUID NOT NULL REFERENCES clean.clean_batch(clean_batch_id),
            _source VARCHAR(32) NOT NULL,
            _available_at TIMESTAMPTZ NOT NULL,
            _quality_status VARCHAR(16) NOT NULL,
            _mapping_version VARCHAR(32) NOT NULL,
            _normalization_version VARCHAR(32) NOT NULL,
            _quality_rule_version VARCHAR(32) NOT NULL,
            _created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            _updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    ''')
    op.execute("CREATE INDEX ix_security_master_exchange_status ON clean.security_master(exchange_code, list_status)")

    op.execute('''
        CREATE TABLE clean.security_master_history (
            security_master_version_id UUID PRIMARY KEY,
            security_code VARCHAR(16) NOT NULL,
            observed_from TIMESTAMPTZ NOT NULL,
            observed_to TIMESTAMPTZ,
            content_hash VARCHAR(64) NOT NULL,
            payload JSONB NOT NULL,
            _clean_batch_id UUID NOT NULL REFERENCES clean.clean_batch(clean_batch_id),
            _created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    ''')
    op.execute("CREATE INDEX ix_security_master_history_code_time ON clean.security_master_history(security_code, observed_from DESC)")

    op.execute('''
        CREATE TABLE clean.stock_daily (
            security_code VARCHAR(16) NOT NULL,
            trade_date DATE NOT NULL,
            open DOUBLE PRECISION,
            high DOUBLE PRECISION,
            low DOUBLE PRECISION,
            close DOUBLE PRECISION,
            pre_close DOUBLE PRECISION,
            change DOUBLE PRECISION,
            pct_change DOUBLE PRECISION,
            volume_share BIGINT,
            amount_cny DOUBLE PRECISION,
            after_hours_volume_share BIGINT,
            after_hours_amount_cny DOUBLE PRECISION,
            _clean_batch_id UUID NOT NULL REFERENCES clean.clean_batch(clean_batch_id),
            _source VARCHAR(32) NOT NULL,
            _available_at TIMESTAMPTZ NOT NULL,
            _quality_status VARCHAR(16) NOT NULL,
            _mapping_version VARCHAR(32) NOT NULL,
            _normalization_version VARCHAR(32) NOT NULL,
            _quality_rule_version VARCHAR(32) NOT NULL,
            _created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            _updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY(security_code, trade_date)
        )
    ''')
    op.execute("CREATE INDEX ix_clean_stock_daily_date_code ON clean.stock_daily(trade_date, security_code)")

    op.execute('''
        CREATE TABLE quality.quality_run (
            quality_run_id UUID PRIMARY KEY,
            task_id UUID NOT NULL REFERENCES ops.collect_task(task_id),
            clean_batch_id UUID NOT NULL REFERENCES clean.clean_batch(clean_batch_id),
            trace_id UUID NOT NULL,
            status VARCHAR(32) NOT NULL,
            quality_rule_version VARCHAR(32) NOT NULL,
            app_version VARCHAR(64) NOT NULL,
            code_revision VARCHAR(64) NOT NULL,
            rules_total INTEGER NOT NULL DEFAULT 0,
            rules_passed INTEGER NOT NULL DEFAULT 0,
            rules_warned INTEGER NOT NULL DEFAULT 0,
            rules_blocked INTEGER NOT NULL DEFAULT 0,
            issues_created INTEGER NOT NULL DEFAULT 0,
            gaps_created INTEGER NOT NULL DEFAULT 0,
            started_at TIMESTAMPTZ NOT NULL,
            finished_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    ''')
    op.execute("CREATE INDEX ix_quality_run_batch_time ON quality.quality_run(clean_batch_id, created_at DESC)")
    op.execute("CREATE INDEX ix_quality_run_trace ON quality.quality_run(trace_id)")

    op.execute('''
        CREATE TABLE quality.quality_issue (
            issue_id UUID PRIMARY KEY,
            quality_run_id UUID NOT NULL REFERENCES quality.quality_run(quality_run_id),
            data_item_id UUID NOT NULL REFERENCES meta.data_item(data_item_id),
            rule_code VARCHAR(64) NOT NULL,
            rule_version VARCHAR(32) NOT NULL,
            dimension VARCHAR(32) NOT NULL,
            severity VARCHAR(16) NOT NULL,
            issue_type VARCHAR(64) NOT NULL,
            status VARCHAR(16) NOT NULL,
            scope_key VARCHAR(512) NOT NULL,
            scope_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            issue_fingerprint VARCHAR(128) NOT NULL,
            observed_value JSONB NOT NULL DEFAULT '{}'::jsonb,
            expected_value JSONB NOT NULL DEFAULT '{}'::jsonb,
            message TEXT NOT NULL,
            first_seen_at TIMESTAMPTZ NOT NULL,
            last_seen_at TIMESTAMPTZ NOT NULL,
            resolved_at TIMESTAMPTZ,
            resolution_type VARCHAR(32),
            resolved_by_quality_run_id UUID,
            related_gap_id UUID,
            repair_attempt_count INTEGER NOT NULL DEFAULT 0,
            auto_repair_exhausted BOOLEAN NOT NULL DEFAULT false,
            next_repair_at TIMESTAMPTZ,
            last_repair_task_id UUID,
            trace_id UUID NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    ''')
    op.execute("CREATE INDEX ix_quality_issue_item_status ON quality.quality_issue(data_item_id, status, last_seen_at DESC)")
    op.execute("CREATE INDEX ix_quality_issue_fingerprint ON quality.quality_issue(issue_fingerprint)")

    op.execute('''
        CREATE TABLE quality.data_gap (
            gap_id UUID PRIMARY KEY,
            data_item_id UUID NOT NULL REFERENCES meta.data_item(data_item_id),
            gap_type VARCHAR(32) NOT NULL,
            status VARCHAR(16) NOT NULL,
            scope_key VARCHAR(512) NOT NULL,
            scope_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            discovered_by_quality_run_id UUID NOT NULL REFERENCES quality.quality_run(quality_run_id),
            discovered_by_issue_id UUID,
            resolved_by_quality_run_id UUID,
            first_seen_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            resolved_at TIMESTAMPTZ,
            trace_id UUID NOT NULL
        )
    ''')

    op.execute('''
        CREATE TABLE quality.issue_task_link (
            issue_task_link_id UUID PRIMARY KEY,
            issue_id UUID NOT NULL REFERENCES quality.quality_issue(issue_id),
            task_id UUID NOT NULL REFERENCES ops.collect_task(task_id),
            action_type VARCHAR(16) NOT NULL,
            created_by VARCHAR(128) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_issue_task_link UNIQUE(issue_id, task_id)
        )
    ''')
    op.execute("CREATE INDEX ix_issue_task_link_task ON quality.issue_task_link(task_id)")

    for item_code in ("trade_calendar", "stock_basic", "stock_daily"):
        for stage in ("clean", "quality"):
            op.execute(f'''
                INSERT INTO ops.task_definition (
                    task_definition_id, task_code, data_item_id, source_binding_id, task_type,
                    update_mode, schedule_rule, availability_rule, split_policy_version,
                    retry_policy_version, priority, enabled, definition_version
                ) VALUES (
                    '{uid(f"taskdef:{stage}:{item_code}")}',
                    '{stage}:{item_code}',
                    '{uid(f"item:{item_code}")}',
                    '{uid(f"binding:tushare:{item_code}")}',
                    '{stage}',
                    'event',
                    '{{}}'::jsonb,
                    '{{}}'::jsonb,
                    'p4-v1',
                    'p4-v1',
                    5,
                    true,
                    'p4-v1'
                ) ON CONFLICT (task_code) DO NOTHING
            ''')


def downgrade() -> None:
    op.execute("DELETE FROM ops.task_definition WHERE task_code IN ('clean:trade_calendar','quality:trade_calendar','clean:stock_basic','quality:stock_basic','clean:stock_daily','quality:stock_daily')")
    op.execute("DROP TABLE IF EXISTS quality.issue_task_link")
    op.execute("DROP TABLE IF EXISTS quality.data_gap")
    op.execute("DROP TABLE IF EXISTS quality.quality_issue")
    op.execute("DROP TABLE IF EXISTS quality.quality_run")
    op.execute("DROP TABLE IF EXISTS clean.stock_daily")
    op.execute("DROP TABLE IF EXISTS clean.security_master_history")
    op.execute("DROP TABLE IF EXISTS clean.security_master")
    op.execute("DROP TABLE IF EXISTS clean.trade_calendar")
    op.execute("DROP TABLE IF EXISTS clean.clean_candidate_row")
    op.execute("DROP TABLE IF EXISTS clean.clean_batch_input")
    op.execute("DROP TABLE IF EXISTS clean.clean_batch")
    op.execute("DROP TABLE IF EXISTS ops.clean_run")
    op.execute("DROP SCHEMA IF EXISTS clean")
