"""P4 auditable skipped RAW rows

Revision ID: 0010_p4_skip_audit
Revises: 0009_p4_core
Create Date: 2026-07-28
"""
from alembic import op

revision = "0010_p4_skip_audit"
down_revision = "0009_p4_core"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('''
        CREATE TABLE clean.clean_skipped_row (
            skipped_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            clean_batch_id UUID NOT NULL REFERENCES clean.clean_batch(clean_batch_id),
            raw_batch_id UUID NOT NULL REFERENCES raw.raw_batch(raw_batch_id),
            raw_record_id BIGINT,
            source_record_key JSONB NOT NULL DEFAULT '{}'::jsonb,
            reason_code VARCHAR(64) NOT NULL,
            details JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    ''')
    op.execute("CREATE INDEX ix_clean_skipped_row_batch ON clean.clean_skipped_row(clean_batch_id)")
    op.execute("CREATE INDEX ix_clean_skipped_row_reason ON clean.clean_skipped_row(reason_code, created_at DESC)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS clean.clean_skipped_row")
